pipeline{
    agent any
    tools{
    maven 'Maven 3.6.1'
    }
    stages{
        stage("build"){
            steps{
                echo "This is a stage first build.."
                dir("worker"){
                sh 'mvn compile'
                }
            }
        }
        stage("test"){
            steps{
                echo "This is a stage test .."
                sleep 3
            }
        }
        stage("package"){
            steps{
                echo "This is a stage package .."
                sleep 7
            }
        }
    }
    
    post{
        always{
            echo "THis pipeline is completed .."
        }
    }
}
